### ISSUE TITLE
简直 julao

### ISSUE THREAD

**Issue by refparo** [swwind/xepub#2]
这东西正是我需要的（在 Linux 上代替 Edge 作为 EPUB 阅读器的轻量程序

**Comment by swwind** [comment]
So glad you like it.
I hope it works for your book.
Although I wrote this epub reader referring to the epub standard format, it still crashes while opening some book. Once I found there is a single `&` character ending without a `;` character (grammar mistake) in one xml file, and then it crashed while parsing that xml file... How baffling their way of making epub file it is!
