### ISSUE TITLE
undefined:1

### ISSUE THREAD

**Issue by jzq233jzq** [swwind/xepub#4]
为什么会undefined啊（

**Comment by swwind** [comment]
...??
What happened to it...??

**Comment by jzq233jzq** [comment]
QAQ
I can't use it on my laptop,it says "undefined" even when just inputing "xepub"!

**Comment by swwind** [comment]
Is there any screenshots you could provide?

P.S. I'm gonna make a huge update on it... Use material designed...

**Comment by jzq233jzq** [comment]
![233444](https://user-images.githubusercontent.com/30001724/54485984-d40a3100-48bc-11e9-9480-956e7538eecb.png)

**Comment by swwind** [comment]
Try to install the alpha branch with
```
npm install -g xepub@alpha
```

Tell me if problem still exists.

**Comment by jzq233jzq** [comment]
![233](https://user-images.githubusercontent.com/30001724/55083414-7953af00-50de-11e9-8888-b76302632bd8.png)
???

**Comment by swwind** [comment]
Well, I have no idea with that error...
Could you please provide your EPUB file here?
Or it throws error every book?

**Comment by jzq233jzq** [comment]
Every book has this problem... :(

**Comment by swwind** [comment]
I realized what had happened on Windows...
`path.join()` used `\` as the separator on Windows...
And then it crashed...

I'll fix it and publish new version soon.

**Comment by swwind** [comment]
Fixed, if this problem **STILL EXISTS**, please give a screenshot using xepub with `--debug` flag.

**Comment by swwind** [comment]
How's it going? (；･`д･´)

**Comment by swwind** [comment]
All right, I regard it has been fixed...
